import Head from 'next/head'
import Navbar from '@/components/navbar';
import useSocialMedia from '@/lib/useSocialMedia';

export default function Home() {

  const { allSocialMedia } = useSocialMedia();

  return (
    <>
      <Head>
        <title>E2E</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black text-white h-screen flex justify-center items-center relative">
        <Navbar socialNetworks={allSocialMedia} />
        E2E Site
      </main>
    </>
  )
}
